.\" CodeDesigner man page. 
.\" Contact michal.bliznak@gmail.com to correct errors or omissions. 
.TH "CODEDESIGNER" "1" "13 December 2011" "Michal Bližňák" ""
.SH "NAME"
codedesigner \- UML CASE tool for code generation/reverse code engineering
.SH "SYNOPSIS"
.\" Syntax goes here. 
.B codedesigner [\-g][\-h]
.I [filename(s)...]
.SH "DESCRIPTION"
.B codedesigner
CodeDesigner is free and open-source RAD tool suitable for easy creation of various diagrams describing applications' structure and logic and for generation of production-ready source code from them.

Features include generation of C++ or Python code and reverse source code engineering.
.SH "OPTIONS"
.TP 8
.B "\-h, \-\-help"
Displays the list of accepted command\-line arguments.
.TP 8
.B "\-g, \-\-generate"
Generate code from the passed file.
.SH "EXAMPLES"
Generate code from myproject.cdp
.nf 
codedesigner \-\-generate myproject.fbp
.SH "AUTHORS"
.nf 
Michal Bližňák
.fi 
.SH "HISTORY"
2011 \- Initial version
