#!/bin/bash
noubuntu=${1//-*ubuntu*_/-}
tbz2file=${noubuntu//deb/tar.bz2}
outdir=deb-to-tarball-tmp
dpkg -x $1 $outdir
chrpath -r \$ORIGIN/../lib $outdir/usr/bin/codedesigner
mv $outdir/usr/lib/codedesigner/libwx_gtk2u* $outdir/usr/lib/
mv $outdir/usr codedesigner
rm -r $outdir
tar cjf $tbz2file codedesigner
