#ifndef IDS_H_INCLUDED
#define IDS_H_INCLUDED

#define udvMAX_ITEMS 500
#define udvTOOLS_CNT 1000

enum APPIDS
{
    // Toolbar IDs
    IDT_GRID = wxID_HIGHEST + 100,
    IDT_ALIGN_LEFT,
    IDT_ALIGN_RIGHT,
    IDT_ALIGN_TOP,
    IDT_ALIGN_BOTTOM,
    IDT_ALIGN_MIDDLE,
    IDT_ALIGN_CENTER,
    IDT_ALIGN_CIRCLE,
    IDT_ALIGN_MESH,
    IDT_ALIGN_VTREE,
    IDT_ALIGN_HTREE,

    // main menu
	IDM_PROJ_MIN_DIAG_ID,
	IDM_PROJ_MAX_DIAG_ID = IDM_PROJ_MIN_DIAG_ID + udvMAX_ITEMS,
	IDM_VIEW_MIN_PLUGINPANE_ID,

    // constrols
    IDC_TREE_STRUCT = IDM_VIEW_MIN_PLUGINPANE_ID + udvMAX_ITEMS,
    IDC_TREE_CODE,
	IDC_CHOICE_LANGUAGES,
    IDC_CHOICE_GENERATORS,
    IDC_CHOICE_ALGORITHMS,

	// context menu items
	IDM_DELAYED_REMOVE,
	IDM_DELAYED_REMOVEELEMENT,
	IDM_DELAYED_REMOVEALL,
	IDM_DELAYED_EDIT,
	IDM_DELAYED_EDITELEMENT,
	IDM_DELAYED_CUTELEMENT,
	IDM_DELAYED_EDITCODE,

	IDM_DIAG_SHOW = IDM_DELAYED_EDITCODE + udvMAX_ITEMS,
	IDM_DIAG_SHOWPREVIEW,
	IDM_DIAG_REMOVEELEMENT,
	IDM_DIAG_EDITELEMENT,
	IDM_DIAG_NAVIGATETO,
	IDM_DIAG_CLEARVARIABLES,
	IDM_DIAG_CLEARFUNCTIONS,
	
	IDM_CODE_ACCESSTYPE,

	IDM_LOGWND_CLEAR = IDM_CODE_ACCESSTYPE + udvMAX_ITEMS,
	
	IDT_DESIGN_TOOL_ID,
	IDT_PALETTE_MIN_TOOL_ID = IDT_DESIGN_TOOL_ID,
	IDT_PALETTE_MAX_TOOL_ID = IDT_PALETTE_MIN_TOOL_ID + udvTOOLS_CNT,
	
	ID_CODEDESIGNER_HIGHEST = IDT_PALETTE_MAX_TOOL_ID + udvTOOLS_CNT,
};


#endif // IDS_H_INCLUDED
